name: doctor_management_system
description: A Doctor Booking Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  sizer: ^2.0.15
  google_fonts: ^5.1.0
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.2
  syncfusion_flutter_datepicker: ^22.2.10
  table_calendar: ^3.0.9
  intl: ^0.18.1
  provider: ^6.0.5
  graphql_flutter: ^5.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  graphql_codegen: ^0.13.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
